### ISSUE TITLE
feat: Provide source/origin of graphic assets (e.g. icons)

### ISSUE THREAD

**Issue by C-Duv** [AdisonCavani/distro-grub-themes#114]
### Describe the solution you'd like

I'd like to know where the icons assets used in this project comes from.

Because I want to add more in my Ventoy setup (e.g. GParted, UBCD, TrueNAS, Proxmox, …) but keep some coherence between all icons, if I knew where the "original" icons are from I may find similar icons for my ISOs / use cases there.

So please consider adding some "credits" file/section for theses assets, or say if they are all own-made.

### Describe alternatives you've considered

I tried _Google Image_ searching some of the icons to see if I can find a public library they comes from :)

### Contributing

Yes, I am willing to help implement this feature in a PR

**Comment by AdisonCavani** [comment]
Most of the icons/assets came from [vinceliuice/grub2-themes](https://github.com/vinceliuice/grub2-themes) project which is licensed under GNU GPL v3.0.
I added some new icons for themes that have been requested.
The creation process is simple - take existing logo, make it black & white, add a border outside with 50% opacity.

**Comment by C-Duv** [comment]
Thanks, I'll see want I can produce from this and I'll file a PR for the common distributions (if that's OK to you).

**Comment by VPraharsha03** [comment]
@AdisonCavani is there a tutorial or a template, sorry as i'm not able to create perfect icons out of images that i've.

**Comment by AdisonCavani** [comment]
@VPraharsha03 here is a example .psd template for icon. You can use [Photopea](https://www.photopea.com/), it's free.
[arch.zip](https://github.com/AdisonCavani/distro-grub-themes/files/14231802/arch.zip)
