### ISSUE TITLE
Upload .xcf, .psd, etc files for background images

### ISSUE THREAD

**Issue by imapottedplant** [AdisonCavani/distro-grub-themes#127]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I would like to add more brands/distros, and possibly add Spanish language support. To do this, I (and other contributors possibly) would need the files from Photoshop, GIMP, Inkscape, or whichever program was used to create the background images. Then, I could easily make the logos consistent with the branding of the rest of the project. A good place for the files may be the assets folder.

### Describe alternatives you've considered

It would be possible to add images / text to the background images directly, but I would have to worry about alignment, the angle of the graphic on the top, etc. Having access to the "layers" in, for example, Photoshop, would also make it simpler to change the background color if users are interested in that. 

### Additional context

I am willing to add some Spanish language support. This could be accomplished with GIMP scripting. 

### Contributing

Yes, I am willing to help implement this feature in a PR

**Comment by AdisonCavani** [comment]
Project files (a.k.a. templates) are located in [`templates branch`](https://github.com/AdisonCavani/distro-grub-themes/tree/templates).

It's covered inside [Contributing FAQ](https://github.com/AdisonCavani/distro-grub-themes/blob/master/CONTRIBUTING.md#frequently-asked-questions).
