### ISSUE TITLE
Fonts are jaggy and not sharp

### ISSUE THREAD

**Issue by pakosaan** [AdisonCavani/distro-grub-themes#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Font are displayed pixelated, jaggy and not sharp

### Expected Behavior

I want font to render as smooth and clear

### Environment

```markdown
- OS: Fedora 39
- Resolution: 1920x1080
```

### Anything else?

I am using Lenovo theem which uses the terminus font and ubuntu font

**Comment by AdisonCavani** [comment]
Can you send some pictures that show the issue with font clarity?

**Comment by AdisonCavani** [comment]
@pakosaan if you send me a pictures I will reopen the issue.
