### ISSUE TITLE
1366x768 Grub customizer

### ISSUE THREAD

**Issue by sinmineryt** [AdisonCavani/distro-grub-themes#2]
The resolution 1366x768 did not appear in Grub Customizer. You should add that to the documentation, disabling custom resolution worked for me.

**Comment by AdisonCavani** [comment]
You can type it manually

**Comment by sinmineryt** [comment]
I didn't know that, thanks! Maybe add something like "When your resolution does not appear, type it in manually" to the README.md?

**Comment by AdisonCavani** [comment]
Updated README.md. Closing issue
