### ISSUE TITLE
Fedora new logo

### ISSUE THREAD

**Issue by gaumeo3230** [AdisonCavani/distro-grub-themes#20]
Fedora has changed to the new logo for a while, can you update the grub theme with the new logo?

![Fedora_logo_(2021) svg](https://user-images.githubusercontent.com/75545944/126816022-897ae1e0-aa57-42b0-80a0-ca9b72dc287d.png)

**Comment by AdisonCavani** [comment]
I'll update this logo today

**Comment by AdisonCavani** [comment]
Updated Fedora logo to new version - [commit](https://github.com/AdisonCavani/distro-grub-themes/commit/a8661c723662224990141e12c69151fde5baa543)

Until v.2.1 which add more icons and update Fedora Logo, you can download new theme from ```/customize/fedora```. It's a lot of work to compress all themes into .tar package - I'll do this in a few days
