### ISSUE TITLE
Anti aliasing not present in theme

### ISSUE THREAD

**Issue by LamprosPitsillos** [AdisonCavani/distro-grub-themes#21]
**Describe the bug**
Font is really blocky , not smooth at all.

**Screenshots**
Sorry for the picture.
![PXL_20210728_144139178](https://user-images.githubusercontent.com/61395246/127316602-a05a736b-5745-4576-8bc0-9b03ec271c85.jpg)

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Resolution: 1920 x 1080

**Additional context**
Followed the instructions and installed it manually.

**Comment by AdisonCavani** [comment]
I'll try to fix it, but I think Grub doesn't support anti-aliasing, so font might be aliased

**Comment by AdisonCavani** [comment]
After additional research I got to a conclusion, that it's not possible to generate anti-aliased Grub font. Currently Grub support fonts in ``.pf2`` format and there isn't any option to change it.

**Comment by LamprosPitsillos** [comment]
https://lists.gnu.org/archive/html/grub-devel/2010-01/msg00361.html
I found this while researching, is .pff3 a thing? Because i don't see anyone using it.

**Comment by LamprosPitsillos** [comment]
> https://lists.gnu.org/archive/html/grub-devel/2010-01/msg00361.html
> I found this while researching, is .pff3 a thing? Because i don't see anyone using it.

After researching in grub docs, this is not a thing, and sadly i couldn't find a solution, all i can think of is just to use a smaller font size so it's not so obvious that it's blocky.

**Comment by AdisonCavani** [comment]
@LamprosPitsillos I tried generating font with some additional parameters. Can you try if it's better than previous?
Just download [new font](https://github.com/AdisonCavani/distro-grub-themes/tree/master/font) and replace the old one.

**Comment by LamprosPitsillos** [comment]
I cant really tell a difference but i think its better now. Thank you for your time !

**Comment by TKivai** [comment]
I'm also having the same issue, although its not that much of a bother
![IMG_4549](https://user-images.githubusercontent.com/43352194/129235990-bc0e04f6-7258-4e60-9796-d3bb954c49e6.jpg)

But is there a reason why the font in the menu entries is blocky while the text at the bottom is smooth(shown below)? Could it be a difference in font families?

![IMG_4552](https://user-images.githubusercontent.com/43352194/129236002-24ad6cb6-f790-4bed-98ba-7fd94c8c3bdd.jpg)

**Comment by AdisonCavani** [comment]
This font is on a background image, not rendered by Grub.
