### ISSUE TITLE
Space in the Linux Mint archive file name impedes GRUB from loading it.

### ISSUE THREAD

**Issue by grohan47** [AdisonCavani/distro-grub-themes#23]
The file name for the Linux Mint archive contains a space in it, which impedes grub from loading it up. Getting rid of the space would be beneficial for any Linux newbies who don't know Linux's problems with spaces in filenames.

**Comment by AdisonCavani** [comment]
Fixed in this [commit](https://github.com/AdisonCavani/distro-grub-themes/commit/0c0068da97caf455a0c56c9d0c044d93a40576da). Closing issue
