### ISSUE TITLE
Text is cut off

### ISSUE THREAD

**Issue by he3als** [AdisonCavani/distro-grub-themes#30]
**Describe the bug**
The text is cut off for some entries in GRUB.

**Expected behavior**
I expected it to not be cut off.

**Screenshots**
![IMG_0718](https://user-images.githubusercontent.com/65787561/141013492-c338868e-4921-4e09-b92f-bb0b47052446.jpg)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Resolution: 1280x1024x32 (maximum VBE resolution supported by my graphics card)

**Additional context**
I apologize in advance if this is a user error. I can not go to 1920x1080 in GRUB, I checked `videoinfo` and it simply was not a mode.

**Comment by AdisonCavani** [comment]
You can edit Grub entry name with ``Grub Customizer``, or edit width of the gray bar: edit ``theme.txt`` and change this line in menu_entry:
```
width = 27%
```

**Comment by he3als** [comment]
That worked thank you

**Comment by RafaelLinux** [comment]
Yes, it's same issue, thanks
