### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by MohammadHisham** [AdisonCavani/distro-grub-themes#31]
**Describe the bug**
i am making a arch based distro
i wanted to use your grub theme
i modified your wallpaper
i get the "unable to load the background"

**Expected behavior**
the grub theme should load
[Anita.tar.gz](https://github.com/AdisonCavani/distro-grub-themes/files/7554610/Anita.tar.gz)

**Desktop (please complete the following information):**
 - OS: Arch Based Anita OS
 - 1920 x 1080

**Comment by AdisonCavani** [comment]
Your ``theme.txt`` has incorrect ``desktop-image`` parameter. It should be "anita.png", because that's the filename. Either edit ``theme.txt`` or rename background image to "background.png"

**Comment by MohammadHisham** [comment]
thank you sir
very good grub theme
