### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by lgbaldoni** [AdisonCavani/distro-grub-themes#33]
**Describe the bug**
Distro icon shown for Fedora, but generic (penguin) one shown for openSUSE Leap

**Expected behavior**
Each distro entry to use its specific icon

**Screenshots**
Could take a picture if necessary

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Resolution: 1920x1080

**Additional context**
Using fedora.tar. Unclear on how OS-specific icons are picked and at what stage.

**Comment by AdisonCavani** [comment]
This is issue with Grub entry, not with theme. To customize icon you should add a class, is this case ``--class opensuse``.
[Here](https://unix.stackexchange.com/questions/593562/how-to-add-icon-to-a-custom-grub-boots-script) is a good example how to do this
