### ISSUE TITLE
Acer, Dell, System76, Msi, 

### ISSUE THREAD

**Issue by wchouser3** [AdisonCavani/distro-grub-themes#36]
Hi!

Loving your grub theme. It's just about my favorite. I was wondering if you have any plans to add "Dell, Acer, etc." to your available backgrounds. I have one each of those machines that I'd like to put your theme on. The both dual-boot so my OCD won't let me put one of the distro ones on them.

Thanks for your hard work!

**Comment by AdisonCavani** [comment]
I will add this themes in the near future

**Comment by AdisonCavani** [comment]
- [ ] [Acer](https://github.com/AdisonCavani/distro-grub-themes/commit/f8338f2f1232258721ee59fe82b31b62839ad010)
- [ ] [Dell](https://github.com/AdisonCavani/distro-grub-themes/commit/f41357fdedbebdcf77fbc315dacb0eb7c1166794)
- [ ] System76
- [ ] MSI

**Comment by wchouser3** [comment]
> * [x]  [Acer](https://github.com/AdisonCavani/distro-grub-themes/commit/f8338f2f1232258721ee59fe82b31b62839ad010)
> 
>     * [x]  [Dell](https://github.com/AdisonCavani/distro-grub-themes/commit/f41357fdedbebdcf77fbc315dacb0eb7c1166794)
> 
>     * [x]  [System76](https://github.com/AdisonCavani/distro-grub-themes/commit/45e3de47c0d2bcb9f42f85c3586b3918edd38d06)
> 
>     * [ ]  MSI

excellent!
