### ISSUE TITLE
Request: Remove Fedora

### ISSUE THREAD

**Issue by sebastiaanfranken** [AdisonCavani/distro-grub-themes#40]
With the switch to [grub's blscfg](https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault) in Fedora 30 this has become incompatible with Fedora. If you use this with Fedora 30+ your install will become unbootable, since it overwrites config files and leaves you without (valid) Linux boot targets. If you are dualbooting, the only thing left after using this repo is Windows and your UEFI. If you're not dualbooting, the only thing left is your UEFI.

Both require a near total reinstall of grub to fix it again, which is not something (new/novice) users should have to do.

So, please, if possible: remove Fedora from this repo in it's entirety. I know that's kind of a bomshell, but we don´t want users with unbootable installs because of a incompatible feature with Fedora's grub configuration.

**Comment by AdisonCavani** [comment]
Fixed in [0d494a6](https://github.com/AdisonCavani/distro-grub-themes/commit/0d494a6022d2f4b2e3544b253e24c38cca6633ca)

**Comment by iDevYT** [comment]
you can use it
bc i do
