### ISSUE TITLE
You only fixed the tar for gigabyte-with-hue, not the plain old gigabyte. The issue is still there in the Gigabyte tar.

### ISSUE THREAD

**Issue by grohan47** [AdisonCavani/distro-grub-themes#42]
You only fixed the tar for gigabyte-with-hue, not the plain old gigabyte. The issue is still there in the Gigabyte tar.

_Originally posted by @grohan47 in https://github.com/AdisonCavani/distro-grub-themes/issues/41#issuecomment-1036973445_

**Comment by AdisonCavani** [comment]
I didn't noticed that. Thanks
