### ISSUE TITLE
Request - Slackware

### ISSUE THREAD

**Issue by 0pLuS0** [AdisonCavani/distro-grub-themes#45]
Hello,

Nice looking grub themes, can you please do one for Slackware?

THANKS

P.S. I did build my box with a Asus mobo, so I'll use that in the mean time... 👍

**Comment by AdisonCavani** [comment]
Slackware theme was added in [692710b](https://github.com/AdisonCavani/distro-grub-themes/commit/692710b3571836b5b20fb7e2fd79935fb257af60)
