### ISSUE TITLE
Best install on ventoy

### ISSUE THREAD

**Issue by TheEndBoss-101** [AdisonCavani/distro-grub-themes#46]
What is the best install on ventoy? so that it does not look distorted?
Resolution: 1920x1080
Tree view on

**Comment by AdisonCavani** [comment]
Hi. Installation guide is [here](https://github.com/AdisonCavani/distro-grub-themes#install-theme-in-ventoy). You can set Ventoy resolution - [method 3](https://www.ventoy.net/en/doc_fuzzy_screen.html).
