### ISSUE TITLE
Ventoy menu

### ISSUE THREAD

**Issue by alex2844** [AdisonCavani/distro-grub-themes#48]
Good afternoon.
To begin with, I really like the theme, but I can’t use it because the windows are cut off

![image](https://user-images.githubusercontent.com/18526177/159204861-d4d529d4-3354-4097-95b8-2b98646db734.png)

**Comment by AdisonCavani** [comment]
Hi. This looks like a duplicate of #30. You can modify the theme yourself.

> You can edit Grub entry name with ``Grub Customizer``, or edit width of the gray bar: edit ``theme.txt`` and change this line in boot_menu:
> ```
> width = 27%
> ```
