### ISSUE TITLE
Request - Framework

### ISSUE THREAD

**Issue by Go2Engle** [AdisonCavani/distro-grub-themes#49]
Would it be possible to add the framework(https://frame.work/) logo to your vendor collection? 🙂

**Comment by Go2Engle** [comment]
I guess I'm asking for a theme :) black background white framework logo if possible.

**Comment by civarson** [comment]
@Go2Engle I created a background for myself if you'd like to use it.
![background](https://user-images.githubusercontent.com/444819/163720562-255229cb-39f7-4578-8837-1e3c6b521061.png)

**Comment by Go2Engle** [comment]
> @Go2Engle I created a background for myself if you'd like to use it. ![background](https://user-images.githubusercontent.com/444819/163720562-255229cb-39f7-4578-8837-1e3c6b521061.png)

Thank you that worked great!

@AdisonCavani I'm happy with using @civarson background and creating a custom theme. I'll close the request. Not sure if you wanna add it to your vendors though as I'm sure other Framework guys out there may like to use this as well =]

**Comment by AdisonCavani** [comment]
@Go2Engle I'll add a new Framework theme tommorow

**Comment by AdisonCavani** [comment]
It's now on master branch.

<img src="https://raw.githubusercontent.com/AdisonCavani/distro-grub-themes/master/preview/Framework.png">

**Comment by Go2Engle** [comment]
> It's now on master branch.
> 
> 
> 
> <img src="https://raw.githubusercontent.com/AdisonCavani/distro-grub-themes/master/preview/Framework.png">

Awesome thank you!
