### ISSUE TITLE
XeroLinux Distro

### ISSUE THREAD

**Issue by TechXero** [AdisonCavani/distro-grub-themes#50]
Hey...

I am maintainer of XeroLinux Distro. Would love to see it featured on here.. XeroLinux.xyz is the site. 

Thanks and keep up great work ;)

**Comment by AdisonCavani** [comment]
Hi. It would be nice if you could provide some HQ logos / designs. Just like [Ubuntu](https://design.ubuntu.com/brand/ubuntu-logo/) or [Debian](https://www.debian.org/logos). I managed to find one, but it has a bad quality

**Comment by TechXero** [comment]
there ya go https://xerolinux.xyz/xeroarch.png

**Comment by AdisonCavani** [comment]
Theme is now on master.
