### ISSUE TITLE
Grub-customizer doesn't install the theme

### ISSUE THREAD

**Issue by franzribcek** [AdisonCavani/distro-grub-themes#51]
Hi, I don't know if it's the right place to ask.

Anyway, I've installed `grub-customizer`, downloaded the `asus.tar` file, followed the given instructions but GRUB hasn't changed.

I'm running elementaryOS 6.1 Jòlnir in dual boot with Windows 11.

Thanks in advance and keep up the good work!

**Comment by AdisonCavani** [comment]
Can you post your grub config - ``/etc/default/grub``?
Also, can you check if ``asus`` theme is present in this directory - ``/boot/grub/themes`` ?

**Comment by franzribcek** [comment]
UPDATE: Okay, so, something happened and now the theme was applied correctly. I simply  'sudo apt upgrade` and I could see from terminal that `grub` was setting up the configuration and now everything works. Sorry to bother.
