### ISSUE TITLE
problem with resolution

### ISSUE THREAD

**Issue by jony127** [AdisonCavani/distro-grub-themes#52]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.10]
 - Resolution [e.g. 1920 x 1080]

**Additional context**

**Comment by jony127** [comment]
Hello.

I have installed this theme in debian 11 but I have a problem with the resolution.  It happens to me something similar to what is exposed in another post https://github.com/AdisonCavani/distro-grub-themes/issues/28

The screenshot that he exposes is similar to mine, the letters are cut off.  I have installed it on a laptop with 1366x768 resolution.  I have added that resolution to the grub configuration file but it doesn't work.

Translated with www.DeepL.com/Translator (free version)

**Comment by AdisonCavani** [comment]
You can edit Grub entry name with ``Grub Customizer`` to shorter one, or edit width of the gray bar: edit ``theme.txt`` and change this line in boot_menu:
```
width = 27%
```

1366×768 is 16:9 aspect ratio, so you shouldn't have black bars in Grub. 
You can check your Grub resolution in ``/etc/default/grub``. It should be:
```
GRUB_GFXMODE=1366×768
```

**Comment by jony127** [comment]
ok thanks, it was solved by modifying the width value
