### ISSUE TITLE
Fedora theme missing.

### ISSUE THREAD

**Issue by grohan47** [AdisonCavani/distro-grub-themes#53]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Re-introduction of the fedora theme deleted a couple of commits ago as I have added manual instructions to make it compatible with blscfg in a pull request.

**Describe alternatives you've considered**
**Additional context**

**Comment by grohan47** [comment]
Any update?

**Comment by AdisonCavani** [comment]
I'll revert the commit and add Fedora theme to release
