### ISSUE TITLE
Apt repository gone for grub-customizer and issues with Ubuntu 22.04

### ISSUE THREAD

**Issue by wcbutler** [AdisonCavani/distro-grub-themes#56]
The repository was taken down to get grub-customzer as it was a part of 20.04 and that makes sense to me but it makes the process a bit longer. Also have to use 20.04 repository to get lib1.1. I know these are mainly issues with the customizer but that seems to be a big part of the steps to get it working on Ubuntu systems.

**Comment by grohan47** [comment]
You can try out the manual installation method and see if that works.

**Comment by AdisonCavani** [comment]
I've made changes to README.md. See [cee24c7](https://github.com/AdisonCavani/distro-grub-themes/commit/cee24c74f1d6e6487bc1ee3fe3634af51b41b2f5)
