### ISSUE TITLE
grub2-mkconfig not applying theme with current instructions

### ISSUE THREAD

**Issue by mikky-j** [AdisonCavani/distro-grub-themes#57]
The current configuration given in the `README.md` doesn't work because the instructions included to modify `/etc/default/grub` don't include commenting out the `GRUB_TERMINAL_OUTPUT="console" line`.

Without commenting `GRUB_TERMINAL_OUTPUT="console"`:
```
$ sudo grub2-mkconfig -o test
Generating grub configuration file ...
Found Windows Boot Manager on /dev/sda1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for UEFI Firmware Settings ...
done
```

With commenting `GRUB_TERMINAL_OUTPUT="console"`:
```
$ sudo grub2-mkconfig -o test
Generating grub configuration file ...
Found theme: /boot/grub2/themes/hp/theme.txt
Found Windows Boot Manager on /dev/sda1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for UEFI Firmware Settings ...
done
```

Therefore, in addition to uncommenting and adding `GRUB_GFXMODE=1920x1080` and` GRUB_THEME="/boot/grub2/themes/<theme name>/theme.txt"`, the instructions should include commenting out GRUB_TERMINAL_OUTPUT="console", in order to force the theme files to be generated, as opposed to the simple grub menu.

**Comment by AdisonCavani** [comment]
Ok. I updated the README.md
