### ISSUE TITLE
Request: Add Bedrock linux

### ISSUE THREAD

**Issue by sopyb** [AdisonCavani/distro-grub-themes#58]
I am using Bedrock Linux for a few months now and I am still using the arch theme (from the install I hijacked) and I was quite surprised there's no bedrock linux theme.

**Comment by AdisonCavani** [comment]
Bedrock theme was added in [9275015](https://github.com/AdisonCavani/distro-grub-themes/commit/927501592133031bdd08f4b71fc452c62aa55805) commit
