### ISSUE TITLE
Request: Kubuntu Support

### ISSUE THREAD

**Issue by eight85** [AdisonCavani/distro-grub-themes#59]
You currently support multiple Ubuntu flavors, here's hoping you will consider Kubuntu 
https://kubuntu.org/

**Comment by AdisonCavani** [comment]
Kubuntu theme is now added. See [b50dab1](https://github.com/AdisonCavani/distro-grub-themes/commit/b50dab153304dd1e7fff71f695ea1ed186a727ac)
