### ISSUE TITLE
Fedora 36 Procedure

### ISSUE THREAD

**Issue by Griffen8280** [AdisonCavani/distro-grub-themes#62]
**Describe the bug**
This procedure will not work on Fedora 36 as it writes the primary grub efi configuration to a different place

**Expected behavior**
By changing the grub2-mkconfig command it should create the grub config in the proper location.  This has been tested and is fully functional, my grub theme is the fedora one from this repo.

**Screenshots**
The following is a screenshot of my /etc/default/grub file for reference
![image](https://user-images.githubusercontent.com/42878642/173919340-c26ab07b-f5d1-4458-b805-c68e6f4310be.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Resolution 1920 x 1080

**Additional context**
The command needed to generate the proper cfg file is:
`sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`

**Comment by AdisonCavani** [comment]
There is a [instruction](https://github.com/AdisonCavani/distro-grub-themes#note) in README.md about finding where is the grub folder

**Comment by Griffen8280** [comment]
Where?  I've read through the README.md a few times now and the only part that comes close is when you use grub2-mkconfig to generate the config files but it has them outputting to the /etc folder.  When doing this the config files were not being copied to the correct location and my Grub menu still looked like the default gfxmenu that is standard.  On Fedora 36 (what I'm using) the command `sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg` is generating the config file in the proper place, but using the tutorial you have in the README.md if you added `&& sudo mv grub2.cfg /boot/efi/EFI/fedora && sudo mv grub2-efi.cfg /boot/efi/EFI/fedora` to the end of your generation commands it will then move the files to where they need to be.  I'm guessing that as a function the grub2-mkconfig maybe did this in the past (would explain the `sudo grub2-mkconfig /etc/grub2-efi.cfg` line) however in Fedora 36 that is not happening.

**Comment by mike-ward** [comment]
I also had to run `sudo grub2-mkconfig /etc/grub2-efi.cfg` on Fedora 36.

**Comment by AdisonCavani** [comment]
I will update the README.md, but I personally think, it's getting out of hand.
There are a lot of linux distributions, so covering each, one by one is impossible.
The docs are already too complex, so I will remove specific commands and replace it with generic folder names.
User will have to figure out where is his ``grub`` config located

**Comment by AdisonCavani** [comment]
I updated the documentation. Does it resolve this issue?

**Comment by Griffen8280** [comment]
Yes that will work on a Fedora 36+ setup.  It may be worth it to start a GitHub wiki for this project so I or others could help add distro specific commands for these themes to work with.  That may alleviate some of the strain on you with maintaining the main files and documentation yourself.  As of now though this big is fixed, thank you!

**Comment by mike-ward** [comment]
Agree on the wiki. I was actually going to offer a pull request to update the docs once I saw a response but the wiki is even better. Tried a bunch of different things over the last couple of days but this repo was the only thing that got me to success. +1 for an excellent theme and support.
