### ISSUE TITLE
Lubuntu Support 

### ISSUE THREAD

**Issue by knightofmorning** [AdisonCavani/distro-grub-themes#71]
I am a complete noob and I saw that Kubuntu is supported.What I would like to know is if other Ubuntu Flavours like Lubuntu is supported.

Sorry if my question sounds boring I just wanna know so I can prevent having a messed up system

**Comment by joelsgp** [comment]
The boot themes work the same in Kubuntu, Lubuntu, and many other distrubtions. The files here are just skins with the logo of each distrubtion, so you can use the Ubuntu one just fine on Lubuntu. 

If you want then I guess leave this issue open to ask for a custom Lubuntu logo skin.

**Comment by AdisonCavani** [comment]
I'll start adding new themes in a few days.

**Comment by knightofmorning** [comment]
> The boot themes work the same in Kubuntu, Lubuntu, and many other distrubtions. The files here are just skins with the logo of each distrubtion, so you can use the Ubuntu one just fine on Lubuntu.
> 
> If you want then I guess leave this issue open to ask for a custom Lubuntu logo skin.

Thanks for the response.I think your answer has good logic

**Comment by AdisonCavani** [comment]
Don't close the issue. It will be closed, when I add Lubuntu theme
