### ISSUE TITLE
Unable to change resolution in grub

### ISSUE THREAD

**Issue by tolgaerok** [AdisonCavani/distro-grub-themes#75]
ive added the following into grub as per your instructions but the resolution dosnt change to 1920 (Fedora 36 - grub 2.06??) but thankfully the theme does show.
I have `unicode.pf2` in the` /boot/grub2/fonts`

```
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_GFXPAYLOAD_LINUX=keep
GRUB_GFXMODE="1920x1080x16"
GRUB_CMDLINE_LINUX="zswap.enabled=1 rhgb quiet mitigations=off rd.driver.blacklist=nouveau selinux=0"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG="true"
GRUB_THEME="/boot/grub2/themes/fedora/theme.txt"
```

Ran your recommended grub2 updater:
`sudo grub2-mkconfig -o /etc/grub2.cfg && sudo grub2-mkconfig -o /etc/grub2-efi.cfg && sudo grub2-mkconfig /etc/grub2-efi.cfg`

Also ran:
`sudo sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg `

Grub does not change to the desired resolution and is all big fonted?

**Comment by grohan47** [comment]
Before we begin, follow [these](https://fedoraproject.org/wiki/GRUB_2#Reinstalling_GRUB) instructions to reinstall GRUB. The last command you ran has long been deprecated.

**Comment by grohan47** [comment]
Maybe try omitting the GFX_mode line entirely? My config does not contain that line and auto-adjusts the resolution according to my monitor.

**Comment by tolgaerok** [comment]
Reinstalling the grub as stated on the fedora website will other os be picked up I.e. windows

**Comment by tolgaerok** [comment]
Solved: Resolution now sets to 1920x1080

Followed instructions as follows:
```
rm /boot/efi/EFI/fedora/grub.cfg
rm /boot/grub2/grub.cfg
```
`sudo dnf reinstall shim-* grub2-efi-* grub2-common`

Edited /etc/default/grub2 and added:
```
GRUB_DEFAULT="saved"
GRUB_DISABLE_SUBMENU="true"
GRUB_GFXMODE="1920x1080"
```
Edited /boot/grub2/grub.cfg and changed 
```
if loadfont $font ; then
  set gfxmode=auto
```

to

```
if loadfont $font ; then
  set gfxmode=1920x1080
```
![20220826_174459](https://user-images.githubusercontent.com/110285959/186880848-73831727-c460-421f-ba54-76d5dcab865d.jpg)
