### ISSUE TITLE
Add Huawei D16

### ISSUE THREAD

**Issue by Liionboy** [AdisonCavani/distro-grub-themes#77]
Please add vendor logo for Huawei

**Comment by AdisonCavani** [comment]
@Liionboy Huawei theme was added. I'm closing this issue.

[Download](https://github.com/AdisonCavani/distro-grub-themes/blob/master/themes/huawei.tar)

Preview:

![Huawei theme](https://raw.githubusercontent.com/AdisonCavani/distro-grub-themes/master/preview/Huawei.png)

**Comment by Liionboy** [comment]
after add this theme , nothing on screen even my last used with mint

**Comment by AdisonCavani** [comment]
@Liionboy can you share a photo/video of the issue, you're describing?  

Have you followed [installation guide](https://adison.me/distro-grub-themes/installation/)?

Which method you used to install this theme?

**Comment by Liionboy** [comment]
Is work was my grub menu hideen

**Comment by AdisonCavani** [comment]
Is the issue resolved?

**Comment by Liionboy** [comment]
Yes
