### ISSUE TITLE
Add Emacs theme

### ISSUE THREAD

**Issue by superuser-does** [AdisonCavani/distro-grub-themes#79]
Not a distro but the most important piece of software for some of us!

There are about 3-4 official Emacs logos because of the long history and chaotic nature of Emacs. However, I'd suggest one similar to the E at the top of the [project website](https://www.gnu.org/software/emacs/) which is also the icon of the program.

The official gradient version is [here](https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/images/icons/hicolor/scalable/apps) but I know that's not in the style of your themes. There are 'flat' versions of this E logo available in numerous icon packs for Linux but I couldn't immediately find a good one, apologies.

**Comment by AdisonCavani** [comment]
I already have 60 themes, so I will work on improving them rather then adding new one.
