### ISSUE TITLE
Outdated install instructions for Fedora

### ISSUE THREAD

**Issue by kra-mo** [AdisonCavani/distro-grub-themes#81]
The installation instructions recommend running `sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg` on Fedora UEFI, however `/boot/efi/EFI/fedora/grub.cfg` is no longer used for configuration since Fedora 34. Simply `sudo grub2-mkconfig -o BOOT_GRUB_LOCATION/grub.cfg` should be used.

See https://fedoraproject.org/wiki/Changes/UnifyGrubConfig

Edit: as a response to #62:
`/etc/grub2.cfg` and `/etc/grub2-efi.cfg` are links to `/boot/grub2/grub.cfg`.

Unless modified `/boot/efi/EFI/fedora/grub.cfg` is a file that loads `/boot/grub2/grub.cfg` and will be reset when the package `grub2-common` is updated.

**Comment by grohan47** [comment]
I already have a pull request in the pipeline, but the maintainer has decided to make a wiki for the same.

**Comment by AdisonCavani** [comment]
Checkout new wiki section and propose changes

**Comment by kra-mo** [comment]
My proposed changes are at https://github.com/kra-mo/distro-grub-themes/wiki
