### ISSUE TITLE
Text gets truncated due to smaller width.

### ISSUE THREAD

**Issue by nikhilpal2705** [AdisonCavani/distro-grub-themes#86]
Most of the themes have `width = 27%` under boot_menu of theme.txt which doesn't show complete name of boot entry particularly in Advanced boot option in which kernel version gets truncated.
It should be atleast 50% to show complete boot entry name.
#30 and #37 have already reported similar bugs but this only resolved that particular theme, not others.

**Comment by AdisonCavani** [comment]
This is intentional to make it look good. If you need to change that behavior, you can manually edit `theme.txt` and adjust `width` property.
