### ISSUE TITLE
Request PSD For Background

### ISSUE THREAD

**Issue by sgtcoder** [AdisonCavani/distro-grub-themes#91]
**Is your feature request related to a problem? Please describe.**  
No, it's a missing asset

**Describe the solution you'd like**  
Provided background to have a PSD for to be able to change for different screen resolutions and to have a default background for Windows spin loader

**Describe alternatives you've considered**  
I would have to have a designer create one.

**Additional context**  
Non

**Contributing**
- [ ] I'm willing to open a pull-request and implement this feature myself

**Comment by AdisonCavani** [comment]
Hi. I moved PSD templates to another branch - `templates`
