### ISSUE TITLE
Use the new MSI logo

### ISSUE THREAD

**Issue by sbeve72** [AdisonCavani/distro-grub-themes#97]
The current MSI logo is outdated. MSI has changed their logo. It'd be highly appreciated if you update the theme too.

**Comment by AdisonCavani** [comment]
Can you give me a picture of the updated logo?

**Comment by sbeve72** [comment]
[There](https://www.swirlingovercoffee.com/wp-content/uploads/2020/11/MSI-Business-Logo-2020.jpg)

**Comment by AdisonCavani** [comment]
From what I can see, MSI didn't abandoned the logo that I'm currently using.
The logo you provided is intended for their business laptop series.
I'll stick to the current logo
